export const FETCHING_AREA_DATA = 'AREAS.FETCHING_AREA_DATA';
export const AREA_DATA_FETCHED = 'AREAS.AREA_DATA_FETCHED';

export const OPEN_NEW_AREA_MODAL = 'AREAS.OPEN_NEW_AREA_MODAL';
export const CLOSE_NEW_AREA_MODAL = 'AREAS.CLOSE_NEW_AREA_MODAL';
export const IN_PROGRESS = 'AREAS.IN_PROGRESS';
export const AREA_SUCCESSFULLY_CREATED = 'AREAS.AREA_SUCCESSFULLY_CREATED';
export const SINGLE_AREA_FETCH = 'AREAS.SINGLE_AREA_FETCH';
export const SINGLE_AREA_FETCH_SUCCESSFUL =
  'AREAS.SINGLE_AREA_FETCH_SUCCESSFUL';
export const AREA_CREATION_FAILED = 'AREAS.AREA_CREATION_FAILED';
export const AREA_NOT_FOUND = 'AREAS.AREA_NOT_FOUND';
export const TEMP_UPDATE = 'AREAS.TEMP_UPDATE';
export const TEMP_UPDATE_SUCCESS = 'AREAS.TEMP_UPDATE_SUCCESS';
export const ROUTINE_SUCCESSFULLY_ADDED = 'AREAS.ROUTINE_SUCCESSFULLY_ADDED';
export const OPEN_EDIT_ROUTINE_DIALOG = 'AREAS.OPEN_EDIT_ROUTINE_DIALOG';
export const CLOSE_EDIT_ROUTINE_DIALOG = 'AREAS.CLOSE_EDIT_ROUTINE_DIALOG';
export const RESET_EDIT_ROUTINE_DIALOG = 'AREAS.RESET_EDIT_ROUTINE_DIALOG';
export const ROUTINE_SUCCESSFULLY_DELETED =
  'AREAS.ROUTINE_SUCCESSFULLY_DELETED';
export const AREA_SUCCESSFULLY_DELETED = 'AREAS.AREA_SUCCESSFULLY_DELETED';
export const SET_NODES_SUCCESSFUL = 'AREAS.SET_NODES_SUCCESSFUL';
export const HEATING_TOGGLE_SUCCESS = 'AREAS.HEATING_TOGGLE_SUCCESS';
